// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool2({
  name: "whoami",
  title: "Who am I",
  description: "Return the authenticated user's id and email from the OAuth token.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/syntropic-scan.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var PHI = (1 + Math.sqrt(5)) / 2;
var syntropic_scan_default = defineTool3({
  name: "syntropic_scan",
  title: "Syntropic Resonance Scan",
  description: "Run a resonance scan over an intent vector. Returns coherence (0\u20131), syntropy \u03A6, entropy rate, and suppression band matches.",
  inputSchema: {
    intent: z2.string().min(1).describe("Intent phrase to project onto the field."),
    iterations: z2.number().int().min(1).max(256).default(32)
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: ({ intent, iterations }) => {
    let coherence = 0;
    let entropy = 0;
    for (let n = 0; n < iterations; n++) {
      const seed = [...intent].reduce((a, c) => a + c.charCodeAt(0), 0);
      const phase = (seed * PHI + n) % (2 * Math.PI);
      coherence += Math.abs(Math.cos(phase));
      entropy += Math.abs(Math.sin(phase / PHI));
    }
    coherence = coherence / iterations;
    const entropyRate = entropy / iterations;
    const syntropy = Math.exp(coherence) - entropyRate;
    const suppressed = coherence >= 0.82 && coherence <= 0.88;
    const result = {
      intent,
      iterations,
      coherence: Number(coherence.toFixed(4)),
      syntropy: Number(syntropy.toFixed(4)),
      entropyRate: Number(entropyRate.toFixed(4)),
      suppressionBandMatch: suppressed
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fqlrsjcyrqxgpgyenczq";
var mcp_default = defineMcp({
  name: "syntropic-reality-mcp",
  title: "Syntropic Reality Compiler MCP",
  version: "0.1.0",
  instructions: "Tools for the Syntropic Reality Compiler. Use `echo` to verify connectivity, `whoami` to confirm the signed-in user, and `syntropic_scan` to run a resonance scan over an intent phrase.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, whoami_default, syntropic_scan_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
